name: dev-workflow

on:
  push:
    branches:
      - dev
  schedule:
    - cron: '0 23 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Python
